-- run Helios export script supporting drivers generated by Helios Profile Editor and Capt Zeen modules
dofile(lfs.writedir()..[[Scripts\Helios\HeliosExport14.lua]])

-- example calls for other programs you may have:
-- dofile(lfs.writedir()..[[Scripts\SimShaker.lua]])
-- dofile(lfs.writedir()..[[Scripts\SimShaker-export-core\ExportCore.lua]])
-- dofile(lfs.writedir()..[[Scripts\VAICOMPRO\VAICOMPRO.export.lua]])
-- dofile(lfs.writedir()..[[Scripts\TacviewGameExport.lua]])
-- dofile(lfs.writedir()..[[Mods\Services\DCS-SRS\Scripts\DCS-SimpleRadioStandalone.lua]])
